/********************************************************************/
/*			  Code generated by IinqExecute.java				  */
/********************************************************************/

#if !defined(IINQ_USER_FUNCTIONS_H_)
#define IINQ_USER_FUNCTIONS_H_

#if defined(__cplusplus)
extern "C" {
#endif

#include "../../dictionary/dictionary_types.h"
#include "../../dictionary/dictionary.h"
#include "../iinq.h"
#include "iinq_functions.h"
#include "iinq_execute.h"

void
create_table1(
);

void
print_table_dogs(
	ion_dictionary_t *dictionary
);

iinq_prepared_sql
SQL_prepare(
	char *sql
);

void
setInt(
	iinq_prepared_sql	p,
	int					param_num,
	int					val
);

void
execute(
	iinq_prepared_sql p
);

#if defined(__cplusplus)
}
#endif

#endif
