/********************************************************************/
/*			  Code generated by IinqExecute.java				  */
/********************************************************************/

#if !defined(IINQ_USER_FUNCTIONS_H_)
#define IINQ_USER_FUNCTIONS_H_

#if defined(__cplusplus)
extern "C" {
#endif

#include "../../dictionary/dictionary_types.h"
#include "../../dictionary/dictionary.h"
#include "../iinq.h"
#include "iinq_functions.h"

iinq_prepared_sql
insert_1(
	int		value_1,
	char	*value_2,
	char	*value_3,
	int		value_4,
	char	*value_5
);

void
print_table_0(
	ion_dictionary_t *dictionary
);

iinq_prepared_sql
insert_0(
	int		value_1,
	char	*value_2,
	char	*value_3,
	int		value_4,
	char	*value_5
);

void
print_table_1(
	ion_dictionary_t *dictionary
);

void
print_table_2(
	ion_dictionary_t *dictionary
);

iinq_prepared_sql
insert_2(
	char	*value_1,
	char	*value_2,
	int		value_3
);

void
setParam(
	iinq_prepared_sql	p,
	int					field_num,
	void				*val
);

iinq_field_t
getFieldType(
	iinq_table_id	table_id,
	int				field_num
);

void
update(
	iinq_table_id		table_id,
	iinq_print_table_t	print_function,
	ion_key_type_t		key_type,
	size_t				key_size,
	size_t				value_size,
	int					num_wheres,
	int					num_update,
	...
);

void
drop_table(
	iinq_table_id *table_id
);

void
execute(
	iinq_prepared_sql p
);

void
delete_record(
	iinq_table_id		table_id,
	iinq_print_table_t	print_function,
	ion_key_type_t		key_type,
	size_t				key_size,
	size_t				value_size,
	int					num_fields,
	...
);

void
create_table(
	iinq_table_id		table_id,
	ion_key_type_t		key_type,
	ion_key_size_t		key_size,
	ion_value_size_t	value_size
);

size_t
calculateOffset(
	iinq_table_id	table_id,
	int				field_num
);

#if defined(__cplusplus)
}
#endif

#endif
